version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    default_labels:
      - 'Type: Dependency'
    commit_message:
      prefix: 'chore'
      include_scope: true
    target_branch: 'develop'

  - package_manager: 'docker'
    directory: '/'
    update_schedule: 'daily'
    default_labels:
      - 'Type: Dependency'
    commit_message:
      prefix: 'chore'
      include_scope: true
    target_branch: 'develop'
